INCDIR = -I ../../include 

CFLAGS=-fPIC -g -O3  -Wall -Wextra -Wno-sign-compare \
  -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls \
  -Wstrict-prototypes $(INCDIR) 


OBJECTS = dcphdlc.o dcpmux.o
	
all: $(OBJECTS)

clean:
	rm -f *.o



